### ISSUE TITLE
Cannot find module “query-all-features” or it’s corresponding type declarations 

### ISSUE THREAD

**Issue by Abexdatl** [gavinr/query-all-features#1]
This is a cool thing to use but after installing the package and use it in my code I am getting 

“ Cannot find module “query-all-features” or it’s corresponding type declarations ” at 

import {queryAllFeatures} from “query-all-features”

**Comment by gavinr** [comment]
Thanks for trying. It seems to be working ok for me. Can you please post a step-by-step replication case that demonstrates the issue? Thanks!

**Comment by Abexdatl** [comment]
Thanks for the replay. The steps I followed is what you basically put 

1).  npm install query-all-features … done successfully 

2). In my .ts file I did 

import { queryAllFeaturs } form ‘query-all-features’;

I get the error at the import statement and the error message is “ Cannot find module “query-all-features” or it’s corresponding type declarations ” at …”

**Comment by Abexdatl** [comment]
Actually I see a npm warning as part of installing your pkg … the message is 

“@esri/arcgis-rest-feature-service@4.0.3” requires “@esri/arcgis-rest-portal@^4.0.0” but none is installed

**Comment by gavinr** [comment]
Thanks, but I really need a step-by-step instructions on how to see your issue: starting from a blank folder.

**Comment by Abexdatl** [comment]
I don’t know how much atomic can it get than what I already indicated. 

 install your package and did an import . Which are pretty much the only two things needed to be done to use your package. 
 
And after doing the two things , you would get an error which says “ …is not recognized” . That is the issue .

may be you could provide a sample angular app that uses your package. That way it is proof that your packaging was correctly done .

**Comment by Abexdatl** [comment]
Some of you guys at esri put out some garbage . This is one of them
